import { useEffect, useState } from "react";
import { loadGovernedExperience, runGovernedPreflight, WorkspaceApiError } from "./api";
import { useWorkspaceLanguage } from "./i18n";
import type { GovernedDecision, GovernedExperienceProjection, GovernedPreflightResult } from "./types";

type ViewState = { kind: "loading" } | { kind: "ready"; projection: GovernedExperienceProjection; result: GovernedPreflightResult | null; running: boolean } | { kind: "error"; code: string };

const decisionCopy: Record<GovernedDecision["name"], { ru: string; en: string; explanation: { ru: string; en: string } }> = {
  Authorization: { ru: "Доступ к действию", en: "Action access", explanation: { ru: "Не подтверждено, что действие доступно для выполнения.", en: "The action has not been confirmed as accessible." } },
  "Organizational Authority": { ru: "Полномочия организации", en: "Organization authority", explanation: { ru: "Не подтверждено, что организация уполномочена на это действие.", en: "The organization has not been confirmed as authorized for this action." } },
  "Data Governance": { ru: "Разрешение на использование данных", en: "Data-use permission", explanation: { ru: "Не подтверждено разрешение на использование данных для этой цели.", en: "Permission to use data for this purpose has not been confirmed." } },
  "Consequential Approval": { ru: "Финальное подтверждение действия", en: "Final action approval", explanation: { ru: "Не подтверждено финальное решение для действия с последствиями.", en: "The final decision for a consequential action has not been confirmed." } },
};

function navigate(href: string, event: React.MouseEvent<HTMLAnchorElement>) {
  event.preventDefault();
  window.history.pushState({}, "", href);
  window.dispatchEvent(new PopStateEvent("popstate"));
}

function safeRecheck(projection: GovernedExperienceProjection): boolean {
  const { action } = projection;
  return action.kind === "governed-preflight" && action.available && projection.execution.status === "Waiting" && projection.decisions.length === 4 && projection.decisions.every((decision) => decision.state === "Waiting") && !action.consequential && !action.canonical_mutation_requested && !action.external_effect_requested && !action.authority_provided;
}

function unchangedResult(result: GovernedPreflightResult): boolean {
  return !result.canonical_mutation_performed && !result.external_effect_performed && !result.organizational_authority_provided && !result.consequential_approval_provided;
}

export function Governed({ csrfToken }: { csrfToken: string }) {
  const { text } = useWorkspaceLanguage();
  const [state, setState] = useState<ViewState>({ kind: "loading" });
  const focusId = new URLSearchParams(window.location.search).get("focus");
  useEffect(() => { let cancelled = false; void loadGovernedExperience().then((projection) => { if (!cancelled) setState({ kind: "ready", projection, result: null, running: false }); }).catch((error) => { if (!cancelled) setState({ kind: "error", code: error instanceof WorkspaceApiError ? error.code : "GOVERNED_EXPERIENCE_UNAVAILABLE" }); }); return () => { cancelled = true; }; }, []);
  if (state.kind === "loading") return <section className="governed" aria-live="polite"><p>{text("Загружаем проверку выполнения…", "Loading execution check…")}</p></section>;
  if (state.kind === "error") return <section className="governed governed-unavailable" role="alert"><p className="eyebrow">{text("Проверка выполнения", "Execution check")}</p><h1>{text("Проверка сейчас недоступна.", "The check is unavailable.")}</h1><p>{text("Детали скрыты, пока текущий доступ и сохранённые свидетельства нельзя безопасно перепроверить.", "Details are withheld until current access and retained evidence can be safely rechecked.")}</p><code>{state.code}</code></section>;

  const { projection, result, running } = state;
  const safe = safeRecheck(projection);
  const waiting = projection.execution.status === "Waiting" && projection.decisions.length === 4 && projection.decisions.every((decision) => decision.state === "Waiting");
  const run = async () => { setState({ kind: "ready", projection, result, running: true }); try { setState({ kind: "ready", projection, result: await runGovernedPreflight(csrfToken), running: false }); } catch (error) { setState({ kind: "error", code: error instanceof WorkspaceApiError ? error.code : "GOVERNED_PREFLIGHT_UNAVAILABLE" }); } };
  const backHref = focusId ? `/my-work?focus=${encodeURIComponent(focusId)}` : "/system";
  return <section className="governed" aria-labelledby="governed-title">
    <header className="governed-heading"><p className="eyebrow">{text("Техническая диагностика", "Technical diagnostics")}</p><h1 id="governed-title">{text("Проверка готовности управляемого выполнения", "Governed execution readiness check")}</h1><p>{text("Сейчас конкретное действие не запрошено.", "No concrete action is currently requested.")}</p><p>{text("Эти условия показывают общую готовность потенциального управляемого действия, а не список ваших задач.", "These conditions show general readiness for a potential governed action, not a list of your tasks.")}</p></header>
    <div className="governed-summary" aria-label={text("Текущее состояние выполнения", "Current execution status")}><div><span>{text("Источник", "Source")}</span><strong>{projection.presentation.source}</strong></div><div><span>{text("Статус", "Status")}</span><strong>{waiting ? text("Остановлено безопасно", "Safely stopped") : projection.execution.status}</strong></div></div>
    <section className="context-panel" aria-labelledby="capability-boundary-title"><h2 id="capability-boundary-title">{text("Что это значит", "What this means")}</h2><p>{text("Текущий интерфейс не выдаёт и не заменяет решения, полномочия или согласования.", "This interface does not issue or replace decisions, authority, or approval.")}</p><p>{text("Проверка не изменяет документ, каноническое состояние или внешнюю систему.", "The check does not change a document, canonical state, or an external system.")}</p></section>
    <section className="decision-panel" aria-labelledby="decisions-title"><p className="eyebrow">{text("Условия готовности", "Readiness conditions")}</p><h2 id="decisions-title">{text("Четыре условия управляемого выполнения", "Four governed-execution conditions")}</h2><div className="decision-list">{projection.decisions.map((decision) => { const copy = decisionCopy[decision.name]; return <article key={decision.name} className="decision-card"><div><span>{text(copy.ru, copy.en)}</span><strong>{decision.state === "Waiting" ? text("Не подтверждено", "Not confirmed") : decision.state}</strong></div><p>{text(copy.explanation.ru, copy.explanation.en)}</p></article>; })}</div></section>
    <section className="governed-action-panel" aria-labelledby="governed-action-title">{safe ? <><p className="eyebrow">{text("Безопасная проверка", "Safe check")}</p><h2 id="governed-action-title">{text("Перепроверить состояние", "Re-check status")}</h2><p>{text("Эта проверка заново проверит четыре обязательных условия и сохранит локальный технический результат проверки.", "This check re-evaluates the four required conditions and records a local technical result.")}</p><ul><li>{text("Не изменит документ или данные в ЕИС.", "It will not change the document or EIS data.")}</li><li>{text("Не выполнит внешний эффект и не изменит каноническое состояние.", "It will not perform an external effect or change canonical state.")}</li><li>{text("Не выдаст полномочия и не одобрит действие.", "It will not grant authority or approve an action.")}</li></ul><p>{text("Если недостающие решения не появились, перепроверка не разблокирует задачу.", "If the missing decisions have not appeared, this check will not unblock the task.")}</p><button type="button" disabled={running || !projection.action.available} onClick={() => void run()}>{running ? text("Проверяем состояние…", "Checking status…") : text("Перепроверить состояние", "Re-check status")}</button></> : <><p className="eyebrow">{text("Проверка недоступна", "Check unavailable")}</p><h2 id="governed-action-title">{text("Безопасность действия не подтверждена", "Action safety is not confirmed")}</h2><p>{text("Текущая проекция не доказывает, что это безопасная проверка. Действие не показано.", "The current projection does not prove this is a safe check. The action is withheld.")}</p></>}{result ? <div className="preflight-result" role="status">{unchangedResult(result) ? <><strong>{text("Проверка завершена", "Check complete")}</strong><p>{text("Ничего не изменено. Обязательные решения по-прежнему не подтверждены. Задача остаётся остановленной.", "Nothing changed. Required decisions remain unconfirmed, so the task stays stopped.")}</p></> : <><strong>{text("Результат проверки требует технической оценки", "The check result requires technical review")}</strong><p>{text("Система не может безопасно подтвердить, что ничего не изменилось.", "The system cannot safely confirm that nothing changed.")}</p></>}<p>{text("Техническое свидетельство", "Technical evidence")}: <code>{result.evidence.classification}</code> · SHA-256 <code>{result.evidence.sha256}</code></p></div> : null}</section>
    <a className="task-secondary-action governed-back-link" href={backHref} onClick={(event) => navigate(backHref, event)}>{focusId ? text("Назад к задаче", "Back to task") : text("Назад к настройкам", "Back to Settings")}</a>
    <details className="technical-details"><summary>{text("Техническое основание", "Technical basis")}</summary><p>{text("Точные имена условий, состояния и источники сохранены для проверки, но не нужны для обычной навигации.", "Exact condition names, states, and sources are retained for verification but are not needed for ordinary navigation.")}</p><dl>{projection.decisions.map((decision) => <div key={decision.name}><dt>{decision.name}</dt><dd>{decision.state}: {decision.basis}</dd></div>)}<div><dt>{text("Статус источника", "Source status")}</dt><dd>{projection.execution.status}: {projection.execution.meaning}</dd></div><div><dt>{text("Валидация", "Validation")}</dt><dd>{projection.presentation.validation_status}</dd></div><div><dt>Source Subject</dt><dd><code>{projection.technical.source_subject}</code></dd></div><div><dt>Source Version</dt><dd><code>{projection.technical.source_version}</code></dd></div><div><dt>Execution Subject</dt><dd><code>{projection.technical.execution_subject}</code></dd></div><div><dt>Execution Version</dt><dd><code>{projection.technical.execution_version}</code></dd></div><div><dt>Event Version</dt><dd><code>{projection.technical.event_version}</code></dd></div><div><dt>{text("Контрольная точка восстановления", "Recovery checkpoint")}</dt><dd><code>{projection.technical.checkpoint_id}</code></dd></div><div><dt>{text("Версия runtime", "Runtime release")}</dt><dd><code>{projection.technical.release_sha}</code></dd></div></dl><ul className="provenance-list">{projection.technical.provenance_refs.map((value) => <li key={value}><code>{value}</code></li>)}</ul></details>
  </section>;
}
