import { useEffect, useState } from "react";
import { loadObjectContext, WorkspaceApiError } from "./api";
import { useWorkspaceLanguage } from "./i18n";
import type { ObjectContext } from "./types";

function navigate(href: string) { window.history.pushState({}, "", href); window.dispatchEvent(new PopStateEvent("popstate")); }

function TechnicalDetails({ item }: { item: ObjectContext }) {
  const { text } = useWorkspaceLanguage(); const [revealed, setRevealed] = useState(false);
  return <details className="technical-details"><summary onClick={() => setRevealed(true)}>{text("Точная техническая идентичность и происхождение", "Exact technical identity and provenance")}</summary>{revealed ? <><p>{text("Эти идентификаторы нужны для точной реконструкции, но не для обычной навигации.", "These identifiers are evidence for exact reconstruction. They are not required for ordinary navigation.")}</p><dl><div><dt>{text("Идентификатор Subject", "Subject identity")}</dt><dd><code>{item.technical.subject_identity}</code></dd></div><div><dt>{text("Идентификатор Version", "Version identity")}</dt><dd><code>{item.technical.version_identity}</code></dd></div><div><dt>{text("Версия схемы", "Schema version")}</dt><dd><code>{item.technical.schema_version}</code></dd></div><div><dt>{text("Версия источника", "Source release")}</dt><dd><code>{item.technical.source_release_sha}</code></dd></div>{item.technical.related_execution_subject ? <div><dt>Execution subject</dt><dd><code>{item.technical.related_execution_subject}</code></dd></div> : null}{item.technical.related_execution_version ? <div><dt>Execution version</dt><dd><code>{item.technical.related_execution_version}</code></dd></div> : null}{item.technical.related_event_version ? <div><dt>Event</dt><dd><code>{item.technical.related_event_version}</code></dd></div> : null}{item.technical.related_checkpoint ? <div><dt>{text("Контрольная точка", "Recovery checkpoint")}</dt><dd><code>{item.technical.related_checkpoint}</code></dd></div> : null}</dl><h3>{text("Ссылки происхождения", "Provenance references")}</h3>{item.technical.provenance_refs.length ? <ul className="provenance-list">{item.technical.provenance_refs.map((ref) => <li key={ref}><code>{ref}</code></li>)}</ul> : <p>{text("В текущем источнике ссылки происхождения не объявлены.", "No provenance references are declared in the current retained source.")}</p>}</> : null}</details>;
}

export function ObjectDetail({ objectId }: { objectId: string }) {
  const { text } = useWorkspaceLanguage(); const [item, setItem] = useState<ObjectContext | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; setItem(null); setError(null); void loadObjectContext(objectId).then((value) => { if (!cancelled) setItem(value); }).catch((reason) => { if (!cancelled) setError(reason instanceof WorkspaceApiError ? reason.code : "OBJECT_UNAVAILABLE"); }); return () => { cancelled = true; }; }, [objectId]);
  if (error) return <section className="object-context object-unavailable" role="alert"><p className="eyebrow">{text("Контекст объекта", "Object context")}</p><h1>{text("Объект недоступен", "Object unavailable")}</h1><p>{text("Текущий источник не удалось перепроверить или непрозрачная ссылка больше не разрешается. Защищённые исторические сведения не додумываются.", "The current source could not be revalidated or the opaque reference no longer resolves. No protected existence or historical details are inferred.")}</p><code>{error}</code><button type="button" className="quiet-button" onClick={() => navigate("/search")}>{text("Назад к поиску", "Back to search")}</button></section>;
  if (!item) return <p aria-live="polite">{text("Перепроверяем текущий контекст объекта…", "Revalidating current governed object context…")}</p>;
  return <article className="object-context" aria-labelledby="object-title"><div className="object-heading"><div><p className="eyebrow">{item.kind} · {item.semantic_role}</p><h1 id="object-title">{item.title}</h1><p>{item.summary}</p></div><button type="button" className="quiet-button" onClick={() => navigate("/search")}>{text("Назад к поиску", "Back to search")}</button></div>{item.knowledge_role ? <p className="semantic-warning">{item.knowledge_role}</p> : null}
    <section className="context-panel"><h2>{text("Что это", "What this is")}</h2><p>{item.context.meaning}</p><dl><div><dt>{text("Авторитетный источник", "Authoritative source")}</dt><dd>{item.authority.authoritative_source}</dd></div><div><dt>{text("Режим авторитета", "Authority mode")}</dt><dd>{item.authority.mode}</dd></div><div><dt>{text("Область авторитета", "Authority scope")}</dt><dd>{item.authority.scope}</dd></div><div><dt>{text("Жизненный цикл", "Lifecycle")}</dt><dd>{item.state.lifecycle ?? text("Не указан", "Not declared in retained metadata")}</dd></div><div><dt>{text("Валидация", "Validation")}</dt><dd>{item.state.validation ?? text("Не указана", "Not declared in retained metadata")}</dd></div></dl></section>
    <section className="context-panel"><h2>{text("Контекст и следующий шаг", "Context and next step")}</h2><p>{item.context.process}</p><p><strong>{text("Следующий шаг", "Next step")}:</strong> {item.context.next_step}</p><p className="boundary-note">{text("Этот режим только для чтения не предоставляет Authorization, Organizational Authority или consequential approval.", "This read-only view grants no Authorization, Organizational Authority or consequential approval.")}</p></section>
    {item.governed_preflight ? <section className="context-panel"><h2>{text("Контекст управляемой проверки", "Governed preflight context")}</h2><p><strong>{text("Результат", "Outcome")}: {item.governed_preflight.outcome ?? text("Не указан", "Not declared")}.</strong> {text("Технический доступ не превращается в согласование.", "The Workspace does not turn technical access into approval.")}</p>{item.governed_preflight.waiting_gates.length ? <><p>{text("Ожидающие условия", "Waiting gates")}:</p><ul>{item.governed_preflight.waiting_gates.map((gate) => <li key={gate}>{gate}</li>)}</ul></> : null}<a className="context-action-link" href="/governed" onClick={(e) => { e.preventDefault(); navigate("/governed"); }}>{text("Открыть связанное выполнение и управляемое действие", "Open related execution and governed action")}</a></section> : null}
    <TechnicalDetails item={item} />
  </article>;
}
