import { useEffect, useState } from "react";
import { loadOrganizationComposition, WorkspaceApiError } from "./api";
import { useWorkspaceLanguage } from "./i18n";
import type { OrganizationCompositionProjection, OrganizationLane } from "./types";
import "./Organization.css";

type State = { kind: "loading" } | { kind: "ready"; data: OrganizationCompositionProjection } | { kind: "error"; code: string };
function navigate(href: string, event: React.MouseEvent<HTMLAnchorElement>) { event.preventDefault(); window.history.pushState({}, "", href); window.dispatchEvent(new PopStateEvent("popstate")); }

function Lane({ lane }: { lane: OrganizationLane }) {
  const { text } = useWorkspaceLanguage();
  return <section className="organization-lane" aria-labelledby={`organization-${lane.id}`}><div className="organization-lane-head"><div><p className="eyebrow">{lane.source_boundary}</p><h2 id={`organization-${lane.id}`}>{lane.label}</h2></div><span className={`organization-lane-state state-${lane.state}`}>{lane.state}</span></div><p>{lane.summary}</p>{lane.items.length ? <div className="organization-items">{lane.items.map((item) => <article className="organization-item" key={item.id}><div className="organization-item-meta"><span>{item.kind}</span><span>{item.state}</span></div><h3>{item.label}</h3><p>{item.summary}</p><dl><div><dt>{text("Источник", "Source")}</dt><dd>{item.source}</dd></div><div><dt>{text("Авторитет", "Authority")}</dt><dd>{item.authority}</dd></div><div><dt>{text("Владелец семантики", "Ownership")}</dt><dd>{item.ownership}</dd></div>{item.semantic_note ? <div><dt>{text("Семантика", "Semantics")}</dt><dd>{item.semantic_note}</dd></div> : null}</dl>{item.kind === "project-lens" ? <p className="boundary-note">{text("Только навигационная линза · не каноническая запись Project.", "Navigation lens only · not a canonical Project record.")}</p> : null}<a href={item.href} onClick={(event) => navigate(item.href, event)}>{text("Открыть контекст", "Open context")}</a></article>)}</div> : <p className="boundary-note">{text("В текущем авторизованном снимке этот контур не показывает контекст.", "No context is presented from this lane in the current authorized snapshot.")}</p>}</section>;
}

export function Organization({ organizationLabel }: { organizationLabel: string }) {
  const { text } = useWorkspaceLanguage(); const [state, setState] = useState<State>({ kind: "loading" });
  useEffect(() => { let live = true; void loadOrganizationComposition().then((data) => { if (live) setState({ kind: "ready", data }); }).catch((error) => { if (live) setState({ kind: "error", code: error instanceof WorkspaceApiError ? error.code : "ORGANIZATION_COMPOSITION_UNAVAILABLE" }); }); return () => { live = false; }; }, []);
  if (state.kind === "loading") return <section className="organization-page" aria-live="polite">{text("Собираем контекст организации…", "Composing organization context…")}</section>;
  if (state.kind === "error") return <section className="organization-page" role="alert"><p className="eyebrow">{text("Организация", "Organization composition")}</p><h1>{text("Контекст организации недоступен.", "Organization context is unavailable.")}</h1><p>{text("Не удалось безопасно собрать защищённый контекст источников.", "Protected source context could not be safely composed.")}</p><code>{state.code}</code></section>;
  return <section className="organization-page" aria-labelledby="organization-title"><header className="organization-header"><p className="eyebrow">{text("Организация", "Organization")}</p><h1 id="organization-title">{organizationLabel}</h1><p>{text("Навигационная картина компании: продукты, проекты, знания и задачи.", "Company navigation view: products, projects, knowledge and work.")}</p><p className="boundary-note">{text("Это восстанавливаемое и неавторитетное представление. Оно не создаёт Organizational Authority, отдельную каноническую базу компании, канонический Project и не переносит продуктовую семантику в Kernel.", "This view is rebuildable and non-authoritative. It does not create Organizational Authority, a canonical company database, a canonical Project record, or product/company semantics in the Kernel.")}</p></header>{state.data.health.state !== "ready" ? <div className="organization-health" role="status">{text("Часть источников ограничена или недоступна; отсутствующий контекст скрывается, а не додумывается.", "Some source lanes are degraded or unavailable; unavailable context is withheld rather than guessed.")}</div> : null}<div className="organization-lanes">{state.data.lanes.map((lane) => <Lane lane={lane} key={lane.id} />)}</div></section>;
}
